const NAVIGATE_TYPES = {
	OPEN: 'VUE_TAB_ROUTER_NAVIGATE_OPEN',
	FOCUS: 'VUE_TAB_ROUTER_NAVIGATE_FOCUS',
	RELOAD: 'VUE_TAB_ROUTER_NAVIGATE_RELOAD',
	CLOSE: 'VUE_TAB_ROUTER_NAVIGATE_CLOSE'
}

export { NAVIGATE_TYPES }

export default { NAVIGATE_TYPES }
